# cliff.toml

[changelog]
# A decorated header for the changelog.
header = """
# Changelog
All notable changes to this project will be documented in this file.
"""
# The format of the release body.
body = """
{% if version %}
    ## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
    ## [unreleased]
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }} ([`{{ commit.id | truncate(length=7, end="") }}`]({{ commit.id }}))
    {% endfor %}
{% endfor %}
"""
# The sections of the changelog, ordered by "sort_by".
commit_parsers = [
    { commit_type = "feat", group = "Features" },
    { commit_type = "fix", group = "Bug Fixes" },
    { commit_type = "chore", group = "Chores" },
    { commit_type = "docs", group = "Documentation" },
    { commit_type = "style", group = "Styling" },
    { commit_type = "refactor", group = "Refactoring" },
    { commit_type = "test", group = "Testing" },
]
# The footer of the changelog.
footer = """
<!-- Generated by git-cliff -->
"""
# Remove the commits that are not grouped.
sort_commits = "newest"
# Protect breaking changes from being skipped.
protect_breaking_commits = true
# The string to be prepended to the version number.
prepend = ""
# The tag pattern to use for versioning.
tag_pattern = "v[0-9].*.*"
# Ignore tags that are not version tags.
ignore_tags = "v0.1.0-beta.1"
# The output path for the changelog.
output = "CHANGELOG.md"